// import React from 'react';

// // === NEW: Predefined data, presented as if AI generated it ===
// const aiChallengeData = {
//   theme: "Echoes of the Past",
//   description: "Greetings, quizzer. I have analyzed global knowledge trends and identified 'Ancient Civilizations' and 'World-Changing Inventions' as areas of rising interest. I have curated a unique set of 20 questions designed to test the depths of your historical knowledge. Prepare to be challenged.",
//   endsIn: "4 Days, 8 Hours",
//   reward: "Special 'Time Weaver' Badge + 500 Bonus Points"
// };
// // === END NEW DATA ===

// function WeeklyChallengeModal({ isOpen, onClose }) {
//   if (!isOpen) {
//     return null;
//   }

//   // A simple handler for the start button
//   const handleStartChallenge = () => {
//     alert("Starting the challenge! This would navigate to the special quiz page.");
//     onClose(); // Close the modal after starting
//   };

//   return (
//     <>
//       {/* Backdrop */}
//       <div 
//         className="fixed inset-0 bg-black bg-opacity-70 z-[100] transition-opacity"
//         onClick={onClose}
//       ></div>

//       {/* Modal Content */}
//       <div className="fixed inset-0 z-[110] flex items-center justify-center p-4">
//         <div 
//           className="bg-surface-light dark:bg-surface-dark rounded-xl shadow-2xl w-full max-w-lg transform transition-all"
//         >
//           {/* Modal Header */}
//           <div className="flex justify-between items-center p-5 border-b border-border-light dark:border-border-dark">
//             <h2 className="text-2xl font-bold text-black dark:text-white">Weekly Challenge</h2>
//             <button 
//               onClick={onClose}
//               className="text-black dark:text-gray-300 hover:text-primary dark:hover:text-primary transition-colors text-2xl"
//             >
//               &times;
//             </button>
//           </div>

//           {/* Modal Body */}
//           <div className="p-6 text-center">
          
//             {/* === AI FEATURE BADGE === */}
//             <div className="inline-block bg-primary bg-opacity-20 text-primary-dark dark:text-primary-light font-semibold px-3 py-1 rounded-full text-sm mb-4">
//               ✨ Generated by AI
//             </div>
            
//             {/* Theme */}
//             <h3 className="text-3xl font-bold text-black dark:text-white mb-3">{aiChallengeData.theme}</h3>
            
//             {/* AI-Generated Description */}
//             <p className="text-black dark:text-gray-300 mb-6 italic">
//               "{aiChallengeData.description}"
//             </p>

//             {/* Details */}
//             <div className="flex justify-around mb-8">
//               <div className="text-center">
//                 <div className="text-sm uppercase text-black dark:text-gray-400">Ends In</div>
//                 <div className="text-xl font-bold text-black dark:text-white">{aiChallengeData.endsIn}</div>
//               </div>
//               <div className="text-center">
//                 <div className="text-sm uppercase text-black dark:text-gray-400">Reward</div>
//                 <div className="text-xl font-bold text-black dark:text-white">{aiChallengeData.reward}</div>
//               </div>
//             </div>

//             {/* Action Button */}
//             <button 
//               onClick={handleStartChallenge}
//               className="bg-primary hover:bg-primary-hover text-black px-8 py-3 rounded-lg font-bold text-lg transition-all duration-300 w-full"
//             >
//               Start Challenge
//             </button>

//           </div>
//         </div>
//       </div>
//     </>
//   );
// }

// export default WeeklyChallengeModal;
import React from 'react';

// === AI Challenge Data ===
const aiChallengeData = {
  theme: "Echoes of the Past",
  description:
    "Greetings, quizzer. I have analyzed global knowledge trends and identified 'Ancient Civilizations' and 'World-Changing Inventions' as areas of rising interest. I have curated a unique set of 20 questions designed to test the depths of your historical knowledge. Prepare to be challenged.",
  endsIn: "4 Days, 8 Hours",
  reward: "Special 'Time Weaver' Badge + 500 Bonus Points",
};

function WeeklyChallengeModal({ isOpen, onClose }) {
  if (!isOpen) return null;

  const handleStartChallenge = () => {
    alert("Starting the challenge! This would navigate to the special quiz page.");
    onClose();
  };

  return (
    <>
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-black bg-opacity-70 z-[100] transition-opacity"
        onClick={onClose}
      ></div>

      {/* Modal */}
      <div className="fixed inset-0 z-[110] flex items-center justify-center p-4">
        <div className="w-full max-w-lg rounded-2xl shadow-2xl transform transition-all overflow-hidden bg-[#c5c0b2] text-black dark:bg-black dark:text-white">
          
          {/* Header */}
          <div className="flex justify-between items-center p-5 border-b border-gray-400 dark:border-gray-700 bg-[#c5c0b2] dark:bg-black">
            <h2 className="text-2xl font-bold font-roslindale uppercase">
              Weekly Challenge
            </h2>
            <button
              onClick={onClose}
              className="text-3xl font-bold text-black dark:text-white hover:text-yellow-500 transition"
            >
              &times;
            </button>
          </div>

          {/* Body */}
          <div className="p-6 text-center space-y-6">
            {/* AI Badge */}
            <div className="inline-block bg-yellow-300/40 text-yellow-900 dark:text-yellow-400 font-semibold px-3 py-1 rounded-full text-sm tracking-wide">
              ✨ Generated by AI
            </div>

            {/* Theme */}
            <h3 className="text-3xl font-bold">{aiChallengeData.theme}</h3>

            {/* Description */}
            <p className="italic leading-relaxed px-2">
              "{aiChallengeData.description}"
            </p>

            {/* Details */}
            <div className="flex justify-around items-start gap-4 flex-wrap text-left">
              <div className="flex-1 text-center">
                <div className="text-sm uppercase opacity-70 mb-1">Ends In</div>
                <div className="text-xl font-semibold">
                  {aiChallengeData.endsIn}
                </div>
              </div>
              <div className="flex-1 text-center">
                <div className="text-sm uppercase opacity-70 mb-1">Reward</div>
                <div className="text-xl font-semibold">
                  {aiChallengeData.reward}
                </div>
              </div>
            </div>

            {/* Start Button */}
            <button
              onClick={handleStartChallenge}
              className="w-full py-3 rounded-lg font-bold text-lg transition-all duration-300 bg-yellow-400 text-black hover:bg-yellow-500 dark:bg-yellow-500 dark:hover:bg-yellow-400"
            >
              Start Challenge
            </button>
          </div>
        </div>
      </div>
    </>
  );
}

export default WeeklyChallengeModal;
